name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres-test:
        image: postgres:16
        env:
          POSTGRES_DB: roleclaimstestdb
          POSTGRES_USER: appuser
          POSTGRES_PASSWORD: apppassword
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U appuser -d roleclaimstestdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal